# Generated by Django 4.2.4 on 2024-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty_name', models.CharField(max_length=100)),
            ],
        ),
    ]
