# Generated by Django 4.2.4 on 2024-05-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='difficulty',
            table='tb_difficulty',
        ),
    ]
