# Generated by Django 4.2.4 on 2024-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0004_alter_difficulty_difficulty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty_name',
            field=models.CharField(max_length=100),
        ),
    ]
