# Generated by Django 4.2.4 on 2024-07-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0007_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
