# Generated by Django 4.2.4 on 2024-07-31 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0008_alter_question_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
