# Generated by Django 4.2.4 on 2024-08-01 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0010_alter_question_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_html_text', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('correct_answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('question_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answers', to='questions_app.question')),
            ],
            options={
                'db_table': 'tb_question_answers',
            },
        ),
    ]
