# Generated by Django 4.2.4 on 2024-09-24 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0012_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
