# Generated by Django 4.2.4 on 2024-10-10 21:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_app', '0014_create_view_tv1_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFromView',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('description', models.CharField(max_length=500)),
                ('active', models.CharField(max_length=1)),
                ('difficulty_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tv1_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulties', models.TextField()),
                ('subjects', models.TextField()),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('PENDING', 'Pending')], max_length=10)),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('date_completed', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_assessments',
            },
        ),
    ]
