# Generated by Django 4.2.4 on 2024-10-10 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_app', '0015_questionfromview_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assigned_to',
            field=models.ForeignKey(db_column='assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
