# Generated by Django 4.2.4 on 2024-10-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0016_alter_assessment_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
