# Generated by Django 4.2.4 on 2024-10-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0017_alter_assessment_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
