# Generated by Django 4.2.4 on 2024-10-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0018_assessment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_selected', models.IntegerField(null=True)),
                ('correct_answer', models.IntegerField(null=True)),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessment', to='questions_app.assessment')),
                ('question_id', models.ForeignKey(db_column='question_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_question', to='questions_app.question')),
            ],
            options={
                'db_table': 'tb_assess_questions',
                'managed': True,
            },
        ),
    ]
