# Generated by Django 4.2.4 on 2024-11-09 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0019_assessment_date_to_complete_assessmentquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 22, 52, 551254)),
        ),
    ]
