# Generated by Django 4.2.4 on 2024-11-22 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0020_alter_assessment_date_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 22, 56, 39, 257407)),
        ),
    ]
