# Generated by Django 4.2.4 on 2024-11-30 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0021_alter_assessment_date_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 19, 5, 38, 961851)),
        ),
    ]
